# (display_name, ats_type, slug_or_url)
# ats_type: "lever" | "greenhouse" | "ashby"

COMPANIES = [
    # ── Lever ──────────────────────────────────────────────────────────────
    ("Figure AI",               "lever",      "figureai"),
    ("1X Technologies",         "lever",      "1x"),
    ("Skydio",                  "lever",      "skydio"),
    ("Zipline",                 "lever",      "flyzipline"),
    ("Covariant",               "lever",      "covariant"),
    ("Agility Robotics",        "lever",      "agilityrobotics"),
    ("Shield AI",               "lever",      "shieldai"),
    ("Nuro",                    "lever",      "nuro"),
    ("Robust.AI",               "lever",      "robustai"),
    ("Viam Robotics",           "lever",      "viamrobotics"),
    ("Machina Labs",            "lever",      "machinalabs"),
    ("Bear Robotics",           "lever",      "bearrobotics"),
    ("Berkshire Grey",          "lever",      "berkshiregrey"),
    ("Diligent Robotics",       "lever",      "diligentrobotics"),
    ("Plus One Robotics",       "lever",      "plusonerobotics"),
    ("Skild AI",                "lever",      "skildai"),
    ("Overland AI",             "lever",      "overlandai"),
    ("Dexterity",               "lever",      "dexterity"),
    ("Locus Robotics",          "lever",      "locusrobotics"),
    ("Verdant Robotics",        "lever",      "verdantrobotics"),
    ("Formic",                  "lever",      "formic"),
    ("Tangram Vision",          "lever",      "tangramvision"),

    # ── Greenhouse ─────────────────────────────────────────────────────────
    ("Boston Dynamics",         "greenhouse", "bostondynamics"),
    ("Waymo",                   "greenhouse", "waymo"),
    ("Aurora",                  "greenhouse", "aurora"),
    ("Motional",                "greenhouse", "motional"),
    ("Joby Aviation",           "greenhouse", "jobyaviation"),
    ("Archer Aviation",         "greenhouse", "archeraviation"),
    ("Wisk Aero",               "greenhouse", "wiskaero"),
    ("Symbotic",                "greenhouse", "symbotic"),
    ("Intuitive Surgical",      "greenhouse", "intuitivesurgical"),
    ("Stryker",                 "greenhouse", "stryker"),
    ("Luminar",                 "greenhouse", "luminar"),
    ("Ouster",                  "greenhouse", "ouster"),
    ("Percepto",                "greenhouse", "percepto"),
    ("Torc Robotics",           "greenhouse", "torc"),
    ("Aeva",                    "greenhouse", "aeva"),
    ("Mobileye",                "greenhouse", "mobileye"),
    ("Aescape",                 "greenhouse", "aescape"),
    ("Sarcos Technology",       "greenhouse", "sarcos"),
    ("Bright Machines",         "greenhouse", "brightmachines"),
    ("Outrider",                "greenhouse", "outrider"),
    ("Gatik",                   "greenhouse", "gatik"),
    ("Argo AI",                 "greenhouse", "argoai"),
    ("Agilent Technologies",    "greenhouse", "agilent"),

    # ── Ashby ──────────────────────────────────────────────────────────────
    ("Apptronik",               "ashby",      "apptronik"),
    ("Physical Intelligence",   "ashby",      "physicalintelligence"),
    ("Sanctuary AI",            "ashby",      "sanctuary"),
    ("ANYbotics",               "ashby",      "anybotics"),
    ("Clearpath Robotics",      "ashby",      "clearpath"),
    ("Realtime Robotics",       "ashby",      "realtimerobotics"),
    ("Mytra",                   "ashby",      "mytra"),
    ("The Bot Company",         "ashby",      "thebotcompany"),
    ("Bedrock Robotics",        "ashby",      "bedrock"),
    ("Skild AI",                "ashby",      "skild"),
    ("Codelogic",               "ashby",      "codelogic"),
    ("Machina Labs",            "ashby",      "machinalabs"),
    ("Collaborative Robotics",  "ashby",      "collaborativerobotics"),
    ("Path Robotics",           "ashby",      "pathrobotics"),
    ("Viam",                    "ashby",      "viam"),
    ("Intrinsic",               "ashby",      "intrinsic"),
    ("Dexco",                   "ashby",      "dexco"),
]
